/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users/index'
import { Route as AdminBadgesIndexRouteImport } from './routes/_admin/badges/index'
import { Route as AdminBadgesNewRouteImport } from './routes/_admin/badges/new'
import { Route as AdminBadgesBadgeIdRouteImport } from './routes/_admin/badges/$badgeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBadgesIndexRoute = AdminBadgesIndexRouteImport.update({
  id: '/badges/',
  path: '/badges/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBadgesNewRoute = AdminBadgesNewRouteImport.update({
  id: '/badges/new',
  path: '/badges/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBadgesBadgeIdRoute = AdminBadgesBadgeIdRouteImport.update({
  id: '/badges/$badgeId',
  path: '/badges/$badgeId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/badges/$badgeId': typeof AdminBadgesBadgeIdRoute
  '/badges/new': typeof AdminBadgesNewRoute
  '/badges/': typeof AdminBadgesIndexRoute
  '/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/badges/$badgeId': typeof AdminBadgesBadgeIdRoute
  '/badges/new': typeof AdminBadgesNewRoute
  '/badges': typeof AdminBadgesIndexRoute
  '/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/badges/$badgeId': typeof AdminBadgesBadgeIdRoute
  '/_admin/badges/new': typeof AdminBadgesNewRoute
  '/_admin/badges/': typeof AdminBadgesIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/badges/$badgeId'
    | '/badges/new'
    | '/badges/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/badges/$badgeId' | '/badges/new' | '/badges' | '/users'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/badges/$badgeId'
    | '/_admin/badges/new'
    | '/_admin/badges/'
    | '/_admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/badges/': {
      id: '/_admin/badges/'
      path: '/badges'
      fullPath: '/badges/'
      preLoaderRoute: typeof AdminBadgesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/badges/new': {
      id: '/_admin/badges/new'
      path: '/badges/new'
      fullPath: '/badges/new'
      preLoaderRoute: typeof AdminBadgesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/badges/$badgeId': {
      id: '/_admin/badges/$badgeId'
      path: '/badges/$badgeId'
      fullPath: '/badges/$badgeId'
      preLoaderRoute: typeof AdminBadgesBadgeIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBadgesBadgeIdRoute: typeof AdminBadgesBadgeIdRoute
  AdminBadgesNewRoute: typeof AdminBadgesNewRoute
  AdminBadgesIndexRoute: typeof AdminBadgesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBadgesBadgeIdRoute: AdminBadgesBadgeIdRoute,
  AdminBadgesNewRoute: AdminBadgesNewRoute,
  AdminBadgesIndexRoute: AdminBadgesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
