packages:
  - apps/web
  - apps/admin
  - apps/desktop
  - packages/api-types
  - packages/desktop-native
  - packages/platform

allowBuilds:
  "@sentry/cli": true
  "@swc/core": true
  electron: true
  esbuild: true
  msgpackr-extract: false

nodeLinker: isolated
strictPeerDependencies: false

packageExtensions:
  "@effect/openapi-generator@4.0.0-beta.103":
    dependencies:
      yaml: ^2.8.1

overrides:
  prettier: ^3.8.1
