#pragma once

// clang-format off
#include <cstddef>
#include <cstdint>
#include <array>
#include <string_view>

// Generated by scripts/build.mjs from protocol/media-lifecycle.json.
namespace syrnike::windows_media::protocol {

inline constexpr int kVersion = 4;
inline constexpr std::string_view kSchemaSha256 = "565cf0cda3c157e494316d371486fc61f22eea15e41eb596f9257bc3225c46d1";
inline constexpr std::size_t kControlQueueCapacity = 16;
inline constexpr std::size_t kEventQueueCapacity = 64;
inline constexpr std::size_t kMaximumCredentialLeases = 4;
inline constexpr std::size_t kMaximumRequestIdLength = 256;
inline constexpr std::size_t kMaximumIdentifierLength = 256;
inline constexpr std::size_t kMaximumServerUrlLength = 2048;
inline constexpr std::size_t kMaximumAccessTokenLength = 16384;
inline constexpr std::size_t kMaximumRemoteVideoDemands = 64;
inline constexpr std::size_t kMaximumDiagnosticMetrics = 16;
inline constexpr std::size_t kMaximumDiagnosticFields = 16;
inline constexpr std::size_t kMaximumDiagnosticNameLength = 64;
inline constexpr std::size_t kMaximumDiagnosticValueLength = 256;
inline constexpr std::size_t kMaximumFailureCodeLength = 128;
inline constexpr std::size_t kMaximumFailureMessageLength = 4096;
inline constexpr std::size_t kMaximumFailureStageLength = 128;
inline constexpr std::uint32_t kMaximumRequestDeadlineMs = 5000;
inline constexpr std::uint32_t kRoomConnectDeadlineMs = 12000;
inline constexpr std::uint32_t kRoomDisconnectDeadlineMs = 2000;
inline constexpr std::uint32_t kRoomCancellationDeadlineMs = 2000;
inline constexpr std::uint32_t kStartDeadlineMs = 2000;
inline constexpr std::uint32_t kPingDeadlineMs = 1000;
inline constexpr std::uint32_t kShutdownDeadlineMs = 1000;

namespace fields {
inline constexpr std::array<std::string_view, 4> kFailure = { "code", "message", "stage", "retryable" };
inline constexpr std::array<std::string_view, 3> kCredentialLease = { "leaseId", "serverUrl", "accessToken" };
inline constexpr std::array<std::string_view, 3> kRoomIntent = { "roomId", "participantIdentity", "credentialLeaseId" };
inline constexpr std::array<std::string_view, 2> kRemoteVideoDemand = { "participantIdentity", "publicationId" };
inline constexpr std::array<std::string_view, 8> kEngineDesiredState = { "revision", "room", "microphone", "camera", "screen", "output", "remoteVideoDemand", "rendererId" };
inline constexpr std::array<std::string_view, 6> kEngineSnapshot = { "engineState", "acceptedRevision", "desiredState", "roomState", "roomFailure", "tracks" };
inline constexpr std::array<std::string_view, 2> kMediaSourceQuery = { "revision", "kind" };
inline constexpr std::array<std::string_view, 5> kMediaInventory = { "audio", "cameras", "sources", "video", "microphoneMeter" };
inline constexpr std::array<std::string_view, 4> kMicrophoneMeter = { "revision", "inputLevel", "gateThreshold", "gateOpen" };
inline constexpr std::array<std::string_view, 13> kExportedFrame = { "kind", "generation", "sequence", "slot", "revision", "rendererId", "publicationId", "participantIdentity", "width", "height", "timestamp", "ingressUs", "handle" };
inline constexpr std::array<std::string_view, 3> kFrameRelease = { "generation", "sequence", "slot" };
inline constexpr std::array<std::string_view, 2> kThumbnailQuery = { "revision", "sourceId" };
inline constexpr std::array<std::string_view, 5> kThumbnail = { "type", "revision", "state", "code", "pixels" };
inline constexpr std::array<std::string_view, 3> kAudioInventory = { "revision", "status", "devices" };
inline constexpr std::array<std::string_view, 4> kAudioDevice = { "id", "label", "direction", "isDefault" };
inline constexpr std::array<std::string_view, 3> kCameraInventory = { "revision", "status", "devices" };
inline constexpr std::array<std::string_view, 4> kCameraDevice = { "id", "label", "available", "isDefault" };
inline constexpr std::array<std::string_view, 5> kSourceInventory = { "revision", "complete", "ok", "truncated", "entries" };
inline constexpr std::array<std::string_view, 8> kScreenSource = { "id", "kind", "title", "label", "available", "minimized", "primary", "audioAvailable" };
inline constexpr std::array<std::string_view, 2> kVideoInventory = { "revision", "publications" };
inline constexpr std::array<std::string_view, 3> kVideoPublication = { "participantIdentity", "publicationId", "source" };
}  // namespace fields

namespace event_fields {
inline constexpr std::array<std::string_view, 4> kEngineStateChangedRequired = { "type", "sequence", "previous", "state" };
inline constexpr std::array<std::string_view, 1> kEngineStateChangedOptional = { "failure" };
inline constexpr std::array<std::string_view, 4> kRoomStateChangedRequired = { "type", "sequence", "revision", "state" };
inline constexpr std::array<std::string_view, 1> kRoomStateChangedOptional = { "failure" };
inline constexpr std::array<std::string_view, 6> kTrackStateChangedRequired = { "type", "sequence", "revision", "track", "state", "warning" };
inline constexpr std::array<std::string_view, 1> kTrackStateChangedOptional = { "failure" };
inline constexpr std::array<std::string_view, 3> kFatalEngineFailureRequired = { "type", "sequence", "failure" };
inline constexpr std::array<std::string_view, 0> kFatalEngineFailureOptional = {  };
}  // namespace event_fields

}  // namespace syrnike::windows_media::protocol
// clang-format on
