#pragma once

// clang-format off
#include <cstddef>
#include <cstdint>
#include <array>
#include <string_view>

// Generated by scripts/build.mjs from protocol/media-lifecycle.json.
namespace syrnike::windows_media::protocol {

inline constexpr int kVersion = 3;
inline constexpr std::string_view kSchemaSha256 = "3d68aa01741ac4047ad38e15b0dc7f267f05db1beced3a970d40267e900bf16a";
inline constexpr std::size_t kControlQueueCapacity = 16;
inline constexpr std::size_t kEventQueueCapacity = 64;
inline constexpr std::size_t kMaximumCredentialLeases = 4;
inline constexpr std::size_t kMaximumRequestIdLength = 256;
inline constexpr std::size_t kMaximumIdentifierLength = 256;
inline constexpr std::size_t kMaximumServerUrlLength = 2048;
inline constexpr std::size_t kMaximumAccessTokenLength = 16384;
inline constexpr std::size_t kMaximumRemoteVideoDemands = 64;
inline constexpr std::size_t kMaximumDiagnosticMetrics = 16;
inline constexpr std::size_t kMaximumDiagnosticFields = 16;
inline constexpr std::size_t kMaximumDiagnosticNameLength = 64;
inline constexpr std::size_t kMaximumDiagnosticValueLength = 256;
inline constexpr std::size_t kMaximumFailureCodeLength = 128;
inline constexpr std::size_t kMaximumFailureMessageLength = 4096;
inline constexpr std::size_t kMaximumFailureStageLength = 128;
inline constexpr std::uint32_t kMaximumRequestDeadlineMs = 5000;
inline constexpr std::uint32_t kStartDeadlineMs = 2000;
inline constexpr std::uint32_t kPingDeadlineMs = 1000;
inline constexpr std::uint32_t kShutdownDeadlineMs = 1000;

namespace fields {
inline constexpr std::array<std::string_view, 4> kFailure = { "code", "message", "stage", "retryable" };
inline constexpr std::array<std::string_view, 3> kCredentialLease = { "leaseId", "serverUrl", "accessToken" };
inline constexpr std::array<std::string_view, 3> kRoomIntent = { "roomId", "participantIdentity", "credentialLeaseId" };
inline constexpr std::array<std::string_view, 3> kRemoteVideoDemand = { "participantIdentity", "publicationId", "quality" };
inline constexpr std::array<std::string_view, 7> kEngineDesiredState = { "revision", "room", "microphone", "camera", "screen", "output", "remoteVideoDemand" };
inline constexpr std::array<std::string_view, 6> kEngineSnapshot = { "engineState", "acceptedRevision", "desiredState", "roomState", "roomFailure", "tracks" };
}  // namespace fields

namespace event_fields {
inline constexpr std::array<std::string_view, 4> kEngineStateChangedRequired = { "type", "sequence", "previous", "state" };
inline constexpr std::array<std::string_view, 1> kEngineStateChangedOptional = { "failure" };
inline constexpr std::array<std::string_view, 4> kRoomStateChangedRequired = { "type", "sequence", "revision", "state" };
inline constexpr std::array<std::string_view, 1> kRoomStateChangedOptional = { "failure" };
inline constexpr std::array<std::string_view, 5> kTrackStateChangedRequired = { "type", "sequence", "revision", "track", "state" };
inline constexpr std::array<std::string_view, 0> kTrackStateChangedOptional = {  };
inline constexpr std::array<std::string_view, 3> kFatalEngineFailureRequired = { "type", "sequence", "failure" };
inline constexpr std::array<std::string_view, 0> kFatalEngineFailureOptional = {  };
}  // namespace event_fields

}  // namespace syrnike::windows_media::protocol
// clang-format on
