#pragma once

#include <cstddef>
#include <cstdint>

// Generated by scripts/build.mjs from the TypeScript protocol contract.
namespace syrnike::windows_media::protocol {

inline constexpr int kVersion = 2;
inline constexpr std::size_t kControlQueueCapacity = 16;
inline constexpr std::size_t kEventQueueCapacity = 64;
inline constexpr std::size_t kMaximumIdentifierLength = 256;
inline constexpr std::size_t kMaximumRemoteVideoDemands = 64;
inline constexpr std::size_t kMaximumDiagnosticMetrics = 16;
inline constexpr std::size_t kMaximumDiagnosticFields = 16;
inline constexpr std::uint32_t kMaximumRequestDeadlineMs = 5000;
inline constexpr std::uint32_t kStartDeadlineMs = 2000;
inline constexpr std::uint32_t kPingDeadlineMs = 1000;
inline constexpr std::uint32_t kShutdownDeadlineMs = 1000;

}  // namespace syrnike::windows_media::protocol
