/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MRouteRouteImport } from './routes/m/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MIndexRouteImport } from './routes/m/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as MSettingsRouteImport } from './routes/m/settings'
import { Route as MProfileRouteImport } from './routes/m/profile'
import { Route as MFriendsRouteImport } from './routes/m/friends'
import { Route as LoginResetRouteImport } from './routes/login/reset'
import { Route as LoginResendRouteImport } from './routes/login/resend'
import { Route as LoginRegisterRouteImport } from './routes/login/register'
import { Route as LoginOnboardRouteImport } from './routes/login/onboard'
import { Route as LoginCheckRouteImport } from './routes/login/check'
import { Route as InviteCodeRouteImport } from './routes/invite/$code'
import { Route as DesktopOverlayRouteImport } from './routes/desktop/overlay'
import { Route as AppVoiceDebugRouteImport } from './routes/app/voice-debug'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppFriendsRouteImport } from './routes/app/friends'
import { Route as AdminBadgesRouteImport } from './routes/admin/badges'
import { Route as MCChannelIdRouteImport } from './routes/m/c/$channelId'
import { Route as LoginResetTokenRouteImport } from './routes/login/reset.$token'
import { Route as AppCChannelIdRouteImport } from './routes/app/c/$channelId'
import { Route as MServersServerIdSettingsRouteImport } from './routes/m/servers/$serverId/settings'
import { Route as AppServersServerIdSettingsRouteImport } from './routes/app/servers/$serverId/settings'

const MRouteRoute = MRouteRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MSettingsRoute = MSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MRouteRoute,
} as any)
const MProfileRoute = MProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MRouteRoute,
} as any)
const MFriendsRoute = MFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => MRouteRoute,
} as any)
const LoginResetRoute = LoginResetRouteImport.update({
  id: '/login/reset',
  path: '/login/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResendRoute = LoginResendRouteImport.update({
  id: '/login/resend',
  path: '/login/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRegisterRoute = LoginRegisterRouteImport.update({
  id: '/login/register',
  path: '/login/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOnboardRoute = LoginOnboardRouteImport.update({
  id: '/login/onboard',
  path: '/login/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCheckRoute = LoginCheckRouteImport.update({
  id: '/login/check',
  path: '/login/check',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopOverlayRoute = DesktopOverlayRouteImport.update({
  id: '/desktop/overlay',
  path: '/desktop/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVoiceDebugRoute = AppVoiceDebugRouteImport.update({
  id: '/voice-debug',
  path: '/voice-debug',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MCChannelIdRoute = MCChannelIdRouteImport.update({
  id: '/c/$channelId',
  path: '/c/$channelId',
  getParentRoute: () => MRouteRoute,
} as any)
const LoginResetTokenRoute = LoginResetTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => LoginResetRoute,
} as any)
const AppCChannelIdRoute = AppCChannelIdRouteImport.update({
  id: '/c/$channelId',
  path: '/c/$channelId',
  getParentRoute: () => AppRouteRoute,
} as any)
const MServersServerIdSettingsRoute =
  MServersServerIdSettingsRouteImport.update({
    id: '/servers/$serverId/settings',
    path: '/servers/$serverId/settings',
    getParentRoute: () => MRouteRoute,
  } as any)
const AppServersServerIdSettingsRoute =
  AppServersServerIdSettingsRouteImport.update({
    id: '/servers/$serverId/settings',
    path: '/servers/$serverId/settings',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/m': typeof MRouteRouteWithChildren
  '/admin/badges': typeof AdminBadgesRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/voice-debug': typeof AppVoiceDebugRoute
  '/desktop/overlay': typeof DesktopOverlayRoute
  '/invite/$code': typeof InviteCodeRoute
  '/login/check': typeof LoginCheckRoute
  '/login/onboard': typeof LoginOnboardRoute
  '/login/register': typeof LoginRegisterRoute
  '/login/resend': typeof LoginResendRoute
  '/login/reset': typeof LoginResetRouteWithChildren
  '/m/friends': typeof MFriendsRoute
  '/m/profile': typeof MProfileRoute
  '/m/settings': typeof MSettingsRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/m/': typeof MIndexRoute
  '/app/c/$channelId': typeof AppCChannelIdRoute
  '/login/reset/$token': typeof LoginResetTokenRoute
  '/m/c/$channelId': typeof MCChannelIdRoute
  '/app/servers/$serverId/settings': typeof AppServersServerIdSettingsRoute
  '/m/servers/$serverId/settings': typeof MServersServerIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/voice-debug': typeof AppVoiceDebugRoute
  '/desktop/overlay': typeof DesktopOverlayRoute
  '/invite/$code': typeof InviteCodeRoute
  '/login/check': typeof LoginCheckRoute
  '/login/onboard': typeof LoginOnboardRoute
  '/login/register': typeof LoginRegisterRoute
  '/login/resend': typeof LoginResendRoute
  '/login/reset': typeof LoginResetRouteWithChildren
  '/m/friends': typeof MFriendsRoute
  '/m/profile': typeof MProfileRoute
  '/m/settings': typeof MSettingsRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/m': typeof MIndexRoute
  '/app/c/$channelId': typeof AppCChannelIdRoute
  '/login/reset/$token': typeof LoginResetTokenRoute
  '/m/c/$channelId': typeof MCChannelIdRoute
  '/app/servers/$serverId/settings': typeof AppServersServerIdSettingsRoute
  '/m/servers/$serverId/settings': typeof MServersServerIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/m': typeof MRouteRouteWithChildren
  '/admin/badges': typeof AdminBadgesRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/voice-debug': typeof AppVoiceDebugRoute
  '/desktop/overlay': typeof DesktopOverlayRoute
  '/invite/$code': typeof InviteCodeRoute
  '/login/check': typeof LoginCheckRoute
  '/login/onboard': typeof LoginOnboardRoute
  '/login/register': typeof LoginRegisterRoute
  '/login/resend': typeof LoginResendRoute
  '/login/reset': typeof LoginResetRouteWithChildren
  '/m/friends': typeof MFriendsRoute
  '/m/profile': typeof MProfileRoute
  '/m/settings': typeof MSettingsRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/m/': typeof MIndexRoute
  '/app/c/$channelId': typeof AppCChannelIdRoute
  '/login/reset/$token': typeof LoginResetTokenRoute
  '/m/c/$channelId': typeof MCChannelIdRoute
  '/app/servers/$serverId/settings': typeof AppServersServerIdSettingsRoute
  '/m/servers/$serverId/settings': typeof MServersServerIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/m'
    | '/admin/badges'
    | '/app/friends'
    | '/app/settings'
    | '/app/voice-debug'
    | '/desktop/overlay'
    | '/invite/$code'
    | '/login/check'
    | '/login/onboard'
    | '/login/register'
    | '/login/resend'
    | '/login/reset'
    | '/m/friends'
    | '/m/profile'
    | '/m/settings'
    | '/verify/$token'
    | '/admin/'
    | '/app/'
    | '/login/'
    | '/m/'
    | '/app/c/$channelId'
    | '/login/reset/$token'
    | '/m/c/$channelId'
    | '/app/servers/$serverId/settings'
    | '/m/servers/$serverId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/badges'
    | '/app/friends'
    | '/app/settings'
    | '/app/voice-debug'
    | '/desktop/overlay'
    | '/invite/$code'
    | '/login/check'
    | '/login/onboard'
    | '/login/register'
    | '/login/resend'
    | '/login/reset'
    | '/m/friends'
    | '/m/profile'
    | '/m/settings'
    | '/verify/$token'
    | '/admin'
    | '/app'
    | '/login'
    | '/m'
    | '/app/c/$channelId'
    | '/login/reset/$token'
    | '/m/c/$channelId'
    | '/app/servers/$serverId/settings'
    | '/m/servers/$serverId/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/m'
    | '/admin/badges'
    | '/app/friends'
    | '/app/settings'
    | '/app/voice-debug'
    | '/desktop/overlay'
    | '/invite/$code'
    | '/login/check'
    | '/login/onboard'
    | '/login/register'
    | '/login/resend'
    | '/login/reset'
    | '/m/friends'
    | '/m/profile'
    | '/m/settings'
    | '/verify/$token'
    | '/admin/'
    | '/app/'
    | '/login/'
    | '/m/'
    | '/app/c/$channelId'
    | '/login/reset/$token'
    | '/m/c/$channelId'
    | '/app/servers/$serverId/settings'
    | '/m/servers/$serverId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  MRouteRoute: typeof MRouteRouteWithChildren
  DesktopOverlayRoute: typeof DesktopOverlayRoute
  InviteCodeRoute: typeof InviteCodeRoute
  LoginCheckRoute: typeof LoginCheckRoute
  LoginOnboardRoute: typeof LoginOnboardRoute
  LoginRegisterRoute: typeof LoginRegisterRoute
  LoginResendRoute: typeof LoginResendRoute
  LoginResetRoute: typeof LoginResetRouteWithChildren
  VerifyTokenRoute: typeof VerifyTokenRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/settings': {
      id: '/m/settings'
      path: '/settings'
      fullPath: '/m/settings'
      preLoaderRoute: typeof MSettingsRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/profile': {
      id: '/m/profile'
      path: '/profile'
      fullPath: '/m/profile'
      preLoaderRoute: typeof MProfileRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/m/friends': {
      id: '/m/friends'
      path: '/friends'
      fullPath: '/m/friends'
      preLoaderRoute: typeof MFriendsRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/login/reset': {
      id: '/login/reset'
      path: '/login/reset'
      fullPath: '/login/reset'
      preLoaderRoute: typeof LoginResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/resend': {
      id: '/login/resend'
      path: '/login/resend'
      fullPath: '/login/resend'
      preLoaderRoute: typeof LoginResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/register': {
      id: '/login/register'
      path: '/login/register'
      fullPath: '/login/register'
      preLoaderRoute: typeof LoginRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/onboard': {
      id: '/login/onboard'
      path: '/login/onboard'
      fullPath: '/login/onboard'
      preLoaderRoute: typeof LoginOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/check': {
      id: '/login/check'
      path: '/login/check'
      fullPath: '/login/check'
      preLoaderRoute: typeof LoginCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop/overlay': {
      id: '/desktop/overlay'
      path: '/desktop/overlay'
      fullPath: '/desktop/overlay'
      preLoaderRoute: typeof DesktopOverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/voice-debug': {
      id: '/app/voice-debug'
      path: '/voice-debug'
      fullPath: '/app/voice-debug'
      preLoaderRoute: typeof AppVoiceDebugRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/badges': {
      id: '/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/m/c/$channelId': {
      id: '/m/c/$channelId'
      path: '/c/$channelId'
      fullPath: '/m/c/$channelId'
      preLoaderRoute: typeof MCChannelIdRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/login/reset/$token': {
      id: '/login/reset/$token'
      path: '/$token'
      fullPath: '/login/reset/$token'
      preLoaderRoute: typeof LoginResetTokenRouteImport
      parentRoute: typeof LoginResetRoute
    }
    '/app/c/$channelId': {
      id: '/app/c/$channelId'
      path: '/c/$channelId'
      fullPath: '/app/c/$channelId'
      preLoaderRoute: typeof AppCChannelIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/m/servers/$serverId/settings': {
      id: '/m/servers/$serverId/settings'
      path: '/servers/$serverId/settings'
      fullPath: '/m/servers/$serverId/settings'
      preLoaderRoute: typeof MServersServerIdSettingsRouteImport
      parentRoute: typeof MRouteRoute
    }
    '/app/servers/$serverId/settings': {
      id: '/app/servers/$serverId/settings'
      path: '/servers/$serverId/settings'
      fullPath: '/app/servers/$serverId/settings'
      preLoaderRoute: typeof AppServersServerIdSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminBadgesRoute: AdminBadgesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppFriendsRoute: typeof AppFriendsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVoiceDebugRoute: typeof AppVoiceDebugRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCChannelIdRoute: typeof AppCChannelIdRoute
  AppServersServerIdSettingsRoute: typeof AppServersServerIdSettingsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppFriendsRoute: AppFriendsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVoiceDebugRoute: AppVoiceDebugRoute,
  AppIndexRoute: AppIndexRoute,
  AppCChannelIdRoute: AppCChannelIdRoute,
  AppServersServerIdSettingsRoute: AppServersServerIdSettingsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface MRouteRouteChildren {
  MFriendsRoute: typeof MFriendsRoute
  MProfileRoute: typeof MProfileRoute
  MSettingsRoute: typeof MSettingsRoute
  MIndexRoute: typeof MIndexRoute
  MCChannelIdRoute: typeof MCChannelIdRoute
  MServersServerIdSettingsRoute: typeof MServersServerIdSettingsRoute
}

const MRouteRouteChildren: MRouteRouteChildren = {
  MFriendsRoute: MFriendsRoute,
  MProfileRoute: MProfileRoute,
  MSettingsRoute: MSettingsRoute,
  MIndexRoute: MIndexRoute,
  MCChannelIdRoute: MCChannelIdRoute,
  MServersServerIdSettingsRoute: MServersServerIdSettingsRoute,
}

const MRouteRouteWithChildren =
  MRouteRoute._addFileChildren(MRouteRouteChildren)

interface LoginResetRouteChildren {
  LoginResetTokenRoute: typeof LoginResetTokenRoute
}

const LoginResetRouteChildren: LoginResetRouteChildren = {
  LoginResetTokenRoute: LoginResetTokenRoute,
}

const LoginResetRouteWithChildren = LoginResetRoute._addFileChildren(
  LoginResetRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  MRouteRoute: MRouteRouteWithChildren,
  DesktopOverlayRoute: DesktopOverlayRoute,
  InviteCodeRoute: InviteCodeRoute,
  LoginCheckRoute: LoginCheckRoute,
  LoginOnboardRoute: LoginOnboardRoute,
  LoginRegisterRoute: LoginRegisterRoute,
  LoginResendRoute: LoginResendRoute,
  LoginResetRoute: LoginResetRouteWithChildren,
  VerifyTokenRoute: VerifyTokenRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
