/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as LoginResetRouteImport } from './routes/login/reset'
import { Route as LoginResendRouteImport } from './routes/login/resend'
import { Route as LoginRegisterRouteImport } from './routes/login/register'
import { Route as LoginOnboardRouteImport } from './routes/login/onboard'
import { Route as LoginCheckRouteImport } from './routes/login/check'
import { Route as InviteCodeRouteImport } from './routes/invite/$code'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppFriendsRouteImport } from './routes/app/friends'
import { Route as AppDiscoverRouteImport } from './routes/app/discover'
import { Route as LoginResetTokenRouteImport } from './routes/login/reset.$token'
import { Route as AppCChannelIdRouteImport } from './routes/app/c/$channelId'
import { Route as AppServersServerIdSettingsRouteImport } from './routes/app/servers/$serverId/settings'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResetRoute = LoginResetRouteImport.update({
  id: '/login/reset',
  path: '/login/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResendRoute = LoginResendRouteImport.update({
  id: '/login/resend',
  path: '/login/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRegisterRoute = LoginRegisterRouteImport.update({
  id: '/login/register',
  path: '/login/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginOnboardRoute = LoginOnboardRouteImport.update({
  id: '/login/onboard',
  path: '/login/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCheckRoute = LoginCheckRouteImport.update({
  id: '/login/check',
  path: '/login/check',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRouteRoute,
} as any)
const LoginResetTokenRoute = LoginResetTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => LoginResetRoute,
} as any)
const AppCChannelIdRoute = AppCChannelIdRouteImport.update({
  id: '/c/$channelId',
  path: '/c/$channelId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppServersServerIdSettingsRoute =
  AppServersServerIdSettingsRouteImport.update({
    id: '/servers/$serverId/settings',
    path: '/servers/$serverId/settings',
    getParentRoute: () => AppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/discover': typeof AppDiscoverRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/login/check': typeof LoginCheckRoute
  '/login/onboard': typeof LoginOnboardRoute
  '/login/register': typeof LoginRegisterRoute
  '/login/resend': typeof LoginResendRoute
  '/login/reset': typeof LoginResetRouteWithChildren
  '/verify/$token': typeof VerifyTokenRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/app/c/$channelId': typeof AppCChannelIdRoute
  '/login/reset/$token': typeof LoginResetTokenRoute
  '/app/servers/$serverId/settings': typeof AppServersServerIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/login/check': typeof LoginCheckRoute
  '/login/onboard': typeof LoginOnboardRoute
  '/login/register': typeof LoginRegisterRoute
  '/login/resend': typeof LoginResendRoute
  '/login/reset': typeof LoginResetRouteWithChildren
  '/verify/$token': typeof VerifyTokenRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/app/c/$channelId': typeof AppCChannelIdRoute
  '/login/reset/$token': typeof LoginResetTokenRoute
  '/app/servers/$serverId/settings': typeof AppServersServerIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/discover': typeof AppDiscoverRoute
  '/app/friends': typeof AppFriendsRoute
  '/app/settings': typeof AppSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/login/check': typeof LoginCheckRoute
  '/login/onboard': typeof LoginOnboardRoute
  '/login/register': typeof LoginRegisterRoute
  '/login/resend': typeof LoginResendRoute
  '/login/reset': typeof LoginResetRouteWithChildren
  '/verify/$token': typeof VerifyTokenRoute
  '/app/': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/app/c/$channelId': typeof AppCChannelIdRoute
  '/login/reset/$token': typeof LoginResetTokenRoute
  '/app/servers/$serverId/settings': typeof AppServersServerIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/discover'
    | '/app/friends'
    | '/app/settings'
    | '/invite/$code'
    | '/login/check'
    | '/login/onboard'
    | '/login/register'
    | '/login/resend'
    | '/login/reset'
    | '/verify/$token'
    | '/app/'
    | '/login/'
    | '/app/c/$channelId'
    | '/login/reset/$token'
    | '/app/servers/$serverId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/discover'
    | '/app/friends'
    | '/app/settings'
    | '/invite/$code'
    | '/login/check'
    | '/login/onboard'
    | '/login/register'
    | '/login/resend'
    | '/login/reset'
    | '/verify/$token'
    | '/app'
    | '/login'
    | '/app/c/$channelId'
    | '/login/reset/$token'
    | '/app/servers/$serverId/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/discover'
    | '/app/friends'
    | '/app/settings'
    | '/invite/$code'
    | '/login/check'
    | '/login/onboard'
    | '/login/register'
    | '/login/resend'
    | '/login/reset'
    | '/verify/$token'
    | '/app/'
    | '/login/'
    | '/app/c/$channelId'
    | '/login/reset/$token'
    | '/app/servers/$serverId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  InviteCodeRoute: typeof InviteCodeRoute
  LoginCheckRoute: typeof LoginCheckRoute
  LoginOnboardRoute: typeof LoginOnboardRoute
  LoginRegisterRoute: typeof LoginRegisterRoute
  LoginResendRoute: typeof LoginResendRoute
  LoginResetRoute: typeof LoginResetRouteWithChildren
  VerifyTokenRoute: typeof VerifyTokenRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/reset': {
      id: '/login/reset'
      path: '/login/reset'
      fullPath: '/login/reset'
      preLoaderRoute: typeof LoginResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/resend': {
      id: '/login/resend'
      path: '/login/resend'
      fullPath: '/login/resend'
      preLoaderRoute: typeof LoginResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/register': {
      id: '/login/register'
      path: '/login/register'
      fullPath: '/login/register'
      preLoaderRoute: typeof LoginRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/onboard': {
      id: '/login/onboard'
      path: '/login/onboard'
      fullPath: '/login/onboard'
      preLoaderRoute: typeof LoginOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/check': {
      id: '/login/check'
      path: '/login/check'
      fullPath: '/login/check'
      preLoaderRoute: typeof LoginCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/friends': {
      id: '/app/friends'
      path: '/friends'
      fullPath: '/app/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/login/reset/$token': {
      id: '/login/reset/$token'
      path: '/$token'
      fullPath: '/login/reset/$token'
      preLoaderRoute: typeof LoginResetTokenRouteImport
      parentRoute: typeof LoginResetRoute
    }
    '/app/c/$channelId': {
      id: '/app/c/$channelId'
      path: '/c/$channelId'
      fullPath: '/app/c/$channelId'
      preLoaderRoute: typeof AppCChannelIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/servers/$serverId/settings': {
      id: '/app/servers/$serverId/settings'
      path: '/servers/$serverId/settings'
      fullPath: '/app/servers/$serverId/settings'
      preLoaderRoute: typeof AppServersServerIdSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCChannelIdRoute: typeof AppCChannelIdRoute
  AppServersServerIdSettingsRoute: typeof AppServersServerIdSettingsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCChannelIdRoute: AppCChannelIdRoute,
  AppServersServerIdSettingsRoute: AppServersServerIdSettingsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface LoginResetRouteChildren {
  LoginResetTokenRoute: typeof LoginResetTokenRoute
}

const LoginResetRouteChildren: LoginResetRouteChildren = {
  LoginResetTokenRoute: LoginResetTokenRoute,
}

const LoginResetRouteWithChildren = LoginResetRoute._addFileChildren(
  LoginResetRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  InviteCodeRoute: InviteCodeRoute,
  LoginCheckRoute: LoginCheckRoute,
  LoginOnboardRoute: LoginOnboardRoute,
  LoginRegisterRoute: LoginRegisterRoute,
  LoginResendRoute: LoginResendRoute,
  LoginResetRoute: LoginResetRouteWithChildren,
  VerifyTokenRoute: VerifyTokenRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
