execute_process(COMMAND "${PROBE}" --golden RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE error)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Backend replay failed: ${error}")
endif()
file(READ "${GOLDEN}" expected)
string(JSON actual_normalized GET "${actual}")
string(JSON expected_normalized GET "${expected}")
if(NOT actual_normalized STREQUAL expected_normalized)
  message(FATAL_ERROR "Backend decisions differ from the recorded golden trace")
endif()
