export type {
  NativeMediaAudioMode,
  NativeMediaScreenAudioMode,
  NativeMediaEncoderBackend,
  NativeMediaDeviceInfo,
  NativeMediaEchoCancellationMode,
  NativeMediaNoiseSuppressionMode,
  NativeMediaFrameMethod,
  NativeMediaFrameStats,
  NativeMediaLoopbackMode,
  NativeMediaLiveKitCredentials,
  NativeMediaEngineCapabilities,
  NativeMediaEngineSessionSummary,
  NativeMediaMicrophoneEngineSessionSummary,
  NativeMediaEngineSnapshot,
  NativeMediaScreenEngineSessionSummary,
  NativeMediaMicrophoneSessionStartOptions,
  NativeMicrophoneMetricsEvent,
  NativeMicrophoneRuntimeConfig,
  NativeMicrophonePreviewSession,
  NativeMicrophonePreviewStartOptions,
  NativeMediaSession,
  NativeMediaSessionKind,
  NativeMediaSessionStatus,
  NativeMediaSessionStartOptions,
  NativeMediaSidecarLostEvent,
  NativeMediaScreenSessionStartOptions,
  NativeMediaScreenSessionPrepareOptions,
  NativeMediaState,
  NativeMediaStateEvent,
  NativeMediaStatsEvent,
  NativeMediaTarget,
} from './media'
export type {
  DesktopOverlayBounds,
  DesktopOverlayGameTarget,
  DesktopOverlayParticipant,
  DesktopOverlaySnapshot,
  DesktopOverlayState,
} from './overlay'
export {
  EMPTY_DESKTOP_OVERLAY_SNAPSHOT,
  normalizeDesktopOverlaySnapshot,
} from './overlay'
export type {
  ActivityDetails,
  DesktopDisplayMediaRequest,
  DesktopDisplayMediaSelection,
  DesktopDisplayMediaSource,
  DesktopDisplayMediaSourceType,
  DesktopOs,
  DesktopPlatformInfo,
  DesktopStoredSession,
  DesktopTrayVoiceState,
  DesktopVersions,
  DesktopUpdateState,
  DesktopWindowPreferences,
  HotkeyAction,
  HotkeyActivationEvent,
  HotkeyBinding,
  HotkeyCombo,
  HotkeyRegistrationResult,
  HotkeyRegistrationStatus,
  HotkeyRuntimeStatus,
  NativeInputEvent,
  SyrnikeDesktopApi,
  SyrnikeRuntime,
} from './api'
export { getCapabilities, type PlatformCapabilities } from './capabilities'
export { IPC, type IpcChannel } from './ipc'
export {
  DEFAULT_APPEARANCE_SETTINGS,
  DEFAULT_DESKTOP_LOCAL_SETTINGS,
  DEFAULT_DESKTOP_OVERLAY_SETTINGS,
  DEFAULT_DESKTOP_SOUND_SETTINGS,
  DEFAULT_DESKTOP_VOICE_LISTENER_SETTINGS,
  DEFAULT_DESKTOP_VOICE_SETTINGS,
  DEFAULT_SOUND_AUTHOR_PACK_ID,
  DEFAULT_THEME_ID,
  SOUND_AUTHOR_PACK_IDS,
  normalizeAppearanceColorMode,
  normalizeAppearanceSettings,
  normalizeAppearanceSettingsPatch,
  normalizeDesktopLocalSettings,
  normalizeDesktopLocalSettingsPatch,
  normalizeDesktopOverlaySettings,
  normalizeDesktopOverlaySettingsPatch,
  normalizeDesktopSoundSettings,
  normalizeDesktopSoundSettingsPatch,
  normalizeDesktopVoiceListenerSettings,
  normalizeDesktopVoiceSettings,
  type AppearanceColorMode,
  type AppearanceSettings,
  type AppearanceSettingsPatch,
  type DesktopLocalSettings,
  type DesktopLocalSettingsPatch,
  type DesktopOverlayGameSettings,
  type DesktopOverlaySettings,
  type DesktopOverlaySettingsPatch,
  type DesktopScreenShareCaptureMode,
  type DesktopScreenShareCodec,
  type DesktopScreenShareQualityName,
  type DesktopSoundSettings,
  type DesktopSoundSettingsPatch,
  type DesktopVoiceInputMode,
  type DesktopVoiceListenerSettings,
  type DesktopVoiceListenerSettingsPatch,
  type DesktopVoiceSettings,
  type DesktopVoiceSettingsPatch,
  type SoundAuthorPackId,
} from './settings'
