/** Каналы IPC между renderer (web) и main process. */
export const IPC = {
  versions: 'syrnike-desktop:versions',
  clipboardWriteText: 'syrnike-desktop:clipboard:write-text',
  windowMinimize: 'syrnike-desktop:window:minimize',
  windowMaximize: 'syrnike-desktop:window:maximize',
  windowClose: 'syrnike-desktop:window:close',
  windowIsMaximized: 'syrnike-desktop:window:is-maximized',
  windowShow: 'syrnike-desktop:window:show',
  windowGetPreferences: 'syrnike-desktop:window:get-preferences',
  windowSetCloseToTray: 'syrnike-desktop:window:set-close-to-tray',
  windowSetOpenAtLogin: 'syrnike-desktop:window:set-open-at-login',
  updatesGetState: 'syrnike-desktop:updates:get-state',
  updatesCheck: 'syrnike-desktop:updates:check',
  updatesInstall: 'syrnike-desktop:updates:install',
  updatesStateChanged: 'syrnike-desktop:updates:state-changed',
  activitySet: 'syrnike-desktop:activity:set',
  activityClear: 'syrnike-desktop:activity:clear',
  traySetVoiceState: 'syrnike-desktop:tray:set-voice-state',
  authLoadSession: 'syrnike-desktop:auth:load-session',
  authSaveSession: 'syrnike-desktop:auth:save-session',
  authClearSession: 'syrnike-desktop:auth:clear-session',
  settingsLoad: 'syrnike-desktop:settings:load',
  settingsUpdate: 'syrnike-desktop:settings:update',
  hotkeysGetBindings: 'syrnike-desktop:hotkeys:get-bindings',
  hotkeysSetBindings: 'syrnike-desktop:hotkeys:set-bindings',
  hotkeysSetSuspended: 'syrnike-desktop:hotkeys:set-suspended',
  hotkeysStartRecording: 'syrnike-desktop:hotkeys:start-recording',
  hotkeysStopRecording: 'syrnike-desktop:hotkeys:stop-recording',
  hotkeysGetRuntimeStatus: 'syrnike-desktop:hotkeys:get-runtime-status',
  hotkeysRecordedInput: 'syrnike-desktop:hotkeys:recorded-input',
  hotkeysPressed: 'syrnike-desktop:hotkeys:pressed',
  overlayGetState: 'syrnike-desktop:overlay:get-state',
  overlaySetEnabled: 'syrnike-desktop:overlay:set-enabled',
  overlaySetSnapshot: 'syrnike-desktop:overlay:set-snapshot',
  overlayStateChanged: 'syrnike-desktop:overlay:state-changed',
  mediaRequest: 'syrnike-desktop:media:request',
  mediaGetDisplaySources: 'syrnike-desktop:media:get-display-sources',
  mediaSelectDisplaySource: 'syrnike-desktop:media:select-display-source',
  mediaCancelRequest: 'syrnike-desktop:media:cancel-request',
  mediaOpenDisplayPicker: 'syrnike-desktop:media:open-display-picker',
  mediaListDevices: 'syrnike-desktop:media:list-devices',
  mediaStartMicrophonePreview: 'syrnike-desktop:media:start-microphone-preview',
  mediaStopMicrophonePreview: 'syrnike-desktop:media:stop-microphone-preview',
  mediaPrepareScreenSession: 'syrnike-desktop:media:prepare-screen-session',
  mediaDisconnectPreparedScreenSession:
    'syrnike-desktop:media:disconnect-prepared-screen-session',
  mediaStartSession: 'syrnike-desktop:media:start-session',
  mediaCancelPendingStarts: 'syrnike-desktop:media:cancel-pending-starts',
  mediaConfigureMicrophoneRuntime:
    'syrnike-desktop:media:configure-microphone-runtime',
  mediaSetMicrophoneMuted: 'syrnike-desktop:media:set-microphone-muted',
  mediaReconnectMicrophoneSession:
    'syrnike-desktop:media:reconnect-microphone-session',
  mediaStopSession: 'syrnike-desktop:media:stop-session',
  mediaGetState: 'syrnike-desktop:media:get-state',
  mediaStats: 'syrnike-desktop:media:stats',
  mediaMicrophoneMetrics: 'syrnike-desktop:media:microphone-metrics',
  mediaStateChanged: 'syrnike-desktop:media:state-changed',
  mediaDisplayPickerResolved: 'syrnike-desktop:media:display-picker-resolved',
  mediaStreamEnded: 'syrnike-desktop:media:stream-ended',
  mediaStreamError: 'syrnike-desktop:media:stream-error',
  mediaRuntimeLost: 'syrnike-desktop:media:runtime-lost',
} as const

export type IpcChannel = (typeof IPC)[keyof typeof IPC]
