export const UI_SOUND_EVENTS = [
  'message.default',
  'message.mention',
  'message.reaction',
  'voice.user_join',
  'voice.user_leave',
  'voice.user_move',
  'voice.mute',
  'voice.unmute',
  'voice.deafen',
  'voice.undeafen',
  'voice.disconnect',
  'call.incoming_ring',
  'call.outgoing_ring',
  'call.connected',
  'call.ended',
  'screen_share.started',
  'screen_share.stopped',
  'camera.started',
  'camera.stopped',
] as const

export type SoundEventId = (typeof UI_SOUND_EVENTS)[number]

export const UI_SOUND_EVENT_LABELS: Record<SoundEventId, string> = {
  'message.default': 'Обычное сообщение',
  'message.mention': 'Упоминание',
  'message.reaction': 'Реакция',
  'voice.user_join': 'Пользователь зашел в войс',
  'voice.user_leave': 'Пользователь вышел из войса',
  'voice.user_move': 'Перемещение в войсе',
  'voice.mute': 'Микрофон выключен',
  'voice.unmute': 'Микрофон включен',
  'voice.deafen': 'Полный мут',
  'voice.undeafen': 'Полный размут',
  'voice.disconnect': 'Выход из голосового канала',
  'call.incoming_ring': 'Входящий звонок',
  'call.outgoing_ring': 'Исходящий звонок',
  'call.connected': 'Звонок принят',
  'call.ended': 'Звонок завершен',
  'screen_share.started': 'Стрим включен',
  'screen_share.stopped': 'Стрим выключен',
  'camera.started': 'Камера включена',
  'camera.stopped': 'Камера выключена',
}
